apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-eve
  annotations:
    ves.io/sites: "ves-io-system/sv10-sjc"
spec:
  selector:
    matchLabels:
      app: project-eve
  template:
    metadata:
      labels:
        app: project-eve
    spec:
      serviceAccountName: default
      imagePullSecrets:
        - name: regcred
      containers:
        - name: server
          image: $EVE_IMAGE
          ports:
          - containerPort: 8080
          - containerPort: 8081
          env:
          - name: PORT
            value: "8080"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: project-eve
spec:
  type: ClusterIP
  selector:
    app: project-eve
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: app
    port: 8081
    targetPort: 8081