---
controller:
  healthStatus: true
  appprotect:
    enable: false
  config:
    name: nginx-config
    entries:
      log-format: |
        $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent
        "$http_referer" "$http_user_agent" $upstream_response_time $upstream_status
        "$uri" $request_length $request_time [$proxy_host] [] $upstream_addr $upstream_bytes_sent
        $upstream_response_time $upstream_status $request_id
  service:
    annotations:
      co.elastic.logs/module: nginx
      cloud.google.com/load-balancer-type: "$LOADBALANCER_TYPE"
    loadBalancerIP: $LOADBALANCER_IP
    extraLabels:
      app: kic-nginx-ingress
    customPorts:
    - name: dashboard
      targetPort: 8080
      protocol: TCP
      port: 8080
    - name: prometheus
      targetPort: 9113
      protocol: TCP
      port: 9113
  pod:
    annotations:
      co.elastic.logs/module: nginx
prometheus:
  create: true
  port: 9113
